version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - setup_remote_docker
      - run: 
          command: |
            docker create -v /dcert_path --name dcert alpine:latest /bin/true
            docker cp $DOCKER_CERT_PATH/. dcert:/dcert_path
            apt-get -qq update
            apt-get install -y -qq curl git
            curl -fsSL https://get.docker.com | sh -
            mkdir /opt/docker-slim
            pushd /opt/docker-slim 
            curl -O https://downloads.dockerslim.com/releases/1.29.0/dist_linux.tar.gz 
            tar xf dist_linux.tar.gz 
            mv dist_linux/* . 
            rm dist_linux.tar.gz && rm -rf dist_linux
            popd
            export PATH=$PATH:/opt/docker-slim/
            git clone --recurse-submodules --depth 1 https://github.com/TeamHypersomnia/Hypersomnia .
            docker build -t arccha/hypersomnia:latest .
            # docker-slim build --continue-after 5 --http-probe=false --tag arccha/hypersomnia:latest --include-path /hypersomnia arccha/hypersomnia:latest
            docker run --volumes-from dcert -e DOCKER_HOST=$DOCKER_HOST -e DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH=/dcert_path dslim/docker-slim build --continue-after 5 --http-probe=false --tag arccha/hypersomnia:latest --include-path /hypersomnia arccha/hypersomnia:latest
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
            docker push arccha/hypersomnia:latest
